### PR TITLE
GCC8 for travis

### PR DESCRIPTION
**Pull request by janisozaur**
It seems some tests fail:
```
$ python3 make.py -clean -build -unit_test -${COMPILER} -Debug -x86
<…snip…>
/home/travis/build/janisozaur/acl/tests/sources/core/test_memory_utils.cpp:108: FAILED:
  REQUIRE( padding0 == 4 )
with expansion:
  0 == 4
```

### CODE REVIEW

**Comment by nfrechette** [comment]
Ah yes, I see why, on x86 doubles aren't always aligned to 8 bytes :( I'll fix the unit test this week and I'll ping you to rebase your PR.
Thank you for the contribution!

**Comment by nfrechette** [comment]
If you rebase your branch on the latest `develop`, the unit test should now pass.

**Comment by janisozaur** [comment]
Done. Travis is green now

**Comment by nfrechette** [comment]
Awesome, thanks again!

**Pull request merged**
