### PR TITLE
Add appveyor.yml

### PR DESCRIPTION
**Pull request by janisozaur**
Please [enable AppVeyor](https://ci.appveyor.com/projects/new), free-for-open-source CI service that hosts (amongst others) MSVC toolchains. Once done, you can merge this to automatically build each commit and verify it against MSVC2015 and MSVC2017

### CODE REVIEW

**Comment by nfrechette** [comment]
That is a great idea! I'll check it out and enable it as soon as I can.

**Comment by janisozaur** [comment]
it's around just two clicks (sign in, enable repo). I have some more changes in the pipeline.

**Comment by janisozaur** [comment]
But having a CI will make sure your current main target stays intact.

**Comment by nfrechette** [comment]
This looks good. I'll merge it and test it out and hook up the badge to the readme.

**Pull request merged**
