### PR TITLE
refactor: avoid using strlen to test for empty strings

### PR DESCRIPTION
**Pull request by GermanAizek**
@nfrechette, minor fix, but with frequent use empty() function, it makes sense.

### CODE REVIEW

**Comment by nfrechette** [comment]
Great catch and thank you for the contributions!
I'd appreciate if you could update the commit/PR message to meet the commit linter guidelines.
You can find them here: https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits

**Comment by GermanAizek** [comment]
@nfrechette fix commit here https://github.com/nfrechette/acl/pull/438/commits/3e0b5e07a3b6f9eb36f194eb7acf374fc069d941

**Comment by nfrechette** [comment]
@all-contributors add @GermanAizek as code

**Comment by nfrechette** [comment]
Thank you for your contribution!

**Pull request merged**
