### PR TITLE
Release/1.3

### PR DESCRIPTION
**Pull request by ddeadguyy**
I'm obviously a github noob.  Perhaps this pull request will be smoother sailing.  I'll respond to the points you made in the old pull request here once I find the time.  For now, this version should allow me to sign the CLA.

We didn't expect to push this into a new version of ACL immediately, especially not if 2.0 is almost done.  This is more for preliminary info sharing.  We're happy to reintegrate our edits into the next release, and consider full integration from there.

I made the regression test compatible with ACL_BIND_POSE this time.  I also filled in the code paths we didn't use for track animation, so I can run the regression test.  Finally, note how I've disabled ACL_BIT_RATE until I figure out why it fails regression :|

### CODE REVIEW

**Comment by ddeadguyy** [comment]
### ACL_PACKING

> ACL_PACKING is interesting, do you have numbers for before/after? Did it help much quality/memory/performance wise?

ACL_PACKING is a quality fix, not a memory or performance optimization.  I'm a big fan of co(dec(X)) == X tests, especially at edge cases, so I added some.  When I enable ACL_UNIT_TEST, disabling all of our other changes, I get the following result on my Win10 PC:

> 93% tests passed, 5 tests failed out of 67
> 
> Label Time Summary:
> acl_unit_tests    =   6.53 sec*proc (67 tests)
> affinematrix      =   0.22 sec*proc (2 tests)
> core              =   1.56 sec*proc (18 tests)
> decay             =   0.21 sec*proc (3 tests)
> error             =   0.10 sec*proc (1 test)
> io                =   0.83 sec*proc (6 tests)
> iterator          =   0.09 sec*proc (1 test)
> math              =   4.14 sec*proc (43 tests)
> memory            =   0.87 sec*proc (10 tests)
> packing           =   1.64 sec*proc (14 tests)
> quat              =   0.28 sec*proc (3 tests)
> scalar            =   0.35 sec*proc (3 tests)
> string            =   0.03 sec*proc (1 test)
> transform         =   0.10 sec*proc (2 tests)
> utils             =   0.47 sec*proc (5 tests)
> vector4           =   3.20 sec*proc (33 tests)
> 
> Total Test time (real) =   1.29 sec
> 
> 
> The following tests FAILED:
>          32 - acl_unit_tests:scalar packing math (Failed)
>          56 - acl_unit_tests:pack_vector4_XX (Failed)
>          63 - acl_unit_tests:pack_vector3_XX (Failed)
>          64 - acl_unit_tests:decay_vector3_XX (Failed)
>          66 - acl_unit_tests:pack_vector2_XX (Failed)
> Errors while running CTest

The failures occur at num_bits 2, 3, 4, 6, 8, and 12.  ACL_PACKING fixes them.

It's worth noting that ACL_PACKING is only a half-step towards minimizing quantization error.  If ACL discretized a range between 0.0f and 1.0f with num_bits == 1, it would do this: 0 -> 0.0f, 1 -> 1.0f.  This results in an average error of 0.25f, and worst-case error of 0.5f, for all floats between 0.0f and 1.0f.  Consider this instead: 0 -> 0.25f, 1 -> 0.75f.  Error exists at the endpoints, but average error is only 0.125f, and worst-case error is only 0.25f.

I didn't want to risk changing what might be a key assumption of ACL(perfect endpoints) with significant unit test and **un**packing changes, even though I could have made the unit tests even tougher, and 24 bits would _just work_.  Perhaps I'll circle back to it later.  That's what I meant by these checkin comments:

> Floating point */ with 2^x is precision-friendly...drives our quantization...If our goal was to minimize error within the range, we'd maximize error at the endpoints, so we could stop here.

> I'll be releasing ACL 2.0 in the coming days.

Looking forward to it.  We're happy to do all of this stuff again in the Release/2.0 branch, and consider integrations afterwards,

**Comment by ddeadguyy** [comment]
### ACL_BIT_RATE

> ...I'm not sure if 20-24 would help all that much. Did you measure before/after? Did it help much with the memory footprint?

Take this with a huge grain of salt, considering I just disabled it until I figure out a regression test failure, but _yes_ and _yes_.  For example:

> complex character(229 joints) with several long joint chains
> 
> short walk transition: 
> 	bits 3-19 -> 29.08K 
> 	bits 1-24 -> 27.33K
> 	
> long walk cycle: 
> 	bits 3-19 -> 124.49K
> 	bits 1-24 -> 116.67K

When given the opportunity to pick 1 or 2 instead of 3, or 20-24 instead of 32, animations tend to shrink.  There could be edge cases where picking 24 on a parent instead of 32 leads to picking higher num_bits for children, but it doesn't seem to be common for us.

> ...dropping the largest quaternion component instead of always W and possibly storing the component's sign to avoid the need to bias when interpolating during decompression...mix full width quaternions with variable bit rates...

Those sound like solid(and familiar) ideas, but I wouldn't mind trying to make those features co-exist with extended bit depths, if only in our local version of ACL.  We'll see how that goes.

The hacks required to help 24 bit survive the unit tests are unfortunate.  Tweaking how quantization works would remove all of that(see: **ACL_PACKING**).  Perhaps I'll cap ACL_BIT_RATE at 23 for now.

**Comment by ddeadguyy** [comment]
### ACL_BIND_POSE

> ...simply returns the authored bind pose instead of the identity transform?...skip the default tracks entirely and output nothing. I presume the output buffer already contains the bind pose and you want to avoid overwriting it?

Correct.  My changes to validate_accuracy in acl_compressor.cpp illustrate how a game engine might manage this(set bind pose once, sample many animations and/or times with it).  Simpler characters tend to save 0.5k per animation, complex characters save closer to 2k per animation.  It adds up when you manage a lot of short clips.  Doing nothing is usually a little bit faster than processing a static channel, but the memory savings are more obvious.

We find that bind transforms occur more often than identity transforms, and provide more flexibility WRT things like animation retargeting and pose format optimization(instead of every-joint QTSQTSQTSQTS, consider only-channels-that-move QQQQTTS).

**Comment by ddeadguyy** [comment]
### Integration Plan

Reposted as-is, for posterity.

> With ACL 2.0 coming out in the next few days, I would really hope to avoid doing another ACL 1.4 release. I primarily maintain ACL by myself and I can't afford to split my focus on maintaining multiple releases beyond patch fixes at this time. That being said, I really like what you did here.
> 
> In an ideal world, I'd like these changes split into separate pull requests (to easily measure before/after) towards the develop branch (for the next release since some stuff for ARM is missing) but I understand this represents a significant amount of work.
> 
> Here's what I would propose: let's get these changes merged into a new branch, maybe something like user/ddeadguyy as a reference. That way we can skip the commitlint requirement and we can keep it around (that way you'll get attribution and I'll also add you to the contributors list in the readme). Then we can work towards integrating these into ACL 2.1.
> 
> For ACL_PACKING, I can probably take it almost as-is and just rework the bits that changed since. But I'll want to measure the impact before/after to validate that everything is in order.
> 
> Similarly, ACL_BIT_RATE should port fairly easily but I'll want to measure the impact before/after as well.
> 
> ACL_BIND_POSE is a bit more tricky. The decompression code path has been entirely reworked and the bind pose has been removed for ACL 2.0 so merging this will be problematic. We'll have to rewrite it by hand. I'm also wondering if we can go about this differently. Could you please create a new GitHub issue with your requirements for this part? I'm pretty sure we can get it supported in ACL 2.1. I just want to make sure I understand what you need.
> 
> You can also reach out by email at: zeno490@gmail.com (or on discord) and we can discuss offline if you prefer.

**Comment by ddeadguyy** [comment]
### ACL_BIT_RATE

> Take this with a huge grain of salt, considering I just disabled it until I figure out a regression test failure...

Regression tests have been fixed.  I missed a spot in write_animated_track_data.

**Comment by nfrechette** [comment]
@all-contributors add @ddeadguyy as code, ideas

**Comment by ddeadguyy** [comment]
Closing this pull request, now that every change has been converted to 2.0.

**Pull request closed without merging**
